language: python
python:
  - "3.4"
sudo: false
# command to install dependencies
install:
  - virtualenv --no-site-packages -p python3 .env
  - source .env/bin/activate
  - cp traq/travis_settings.py traq/local_settings.py
  - make install
# command to run tests
script: make test
